apiVersion: v1
kind: Pod
metadata:
  annotations:
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.10-1
    resources:
     limits:
      memory: 
     requests:
      cpu: ""
      memory: 
    securityContext:
      privileged: true

